/**
 * Trash Wars — Drizzle schema (Postgres / PGlite).
 *
 * NOTE: the authoritative DDL lives in src/sql.ts (SCHEMA_STATEMENTS) and is applied by
 * `migrateDb()`. This file must stay in sync with it — it provides the typed query surface.
 * Enum string values are reused from @trash-wars/shared zod contracts where they exist.
 */
import {
  bigint,
  boolean,
  date,
  doublePrecision,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import {
  characterStatus,
  faction,
  missionOutcome,
  missionState,
  type CharacterStats,
  type ProbabilityTable,
} from "@trash-wars/shared";

/* ── Enums ────────────────────────────────────────────────────────── */

export const userRoleEnum = pgEnum("user_role", ["player", "admin"]);
export const accountOwnerTypeEnum = pgEnum("account_owner_type", ["user", "system"]);
export const ACCOUNT_KINDS = [
  "game_balance",
  "treasury",
  "burn_pool",
  "pd_pool",
  "emissions_budget",
  "emissions_reserve",
  "mission_escrow",
  "withdrawals_payable",
  "onchain_reserve_mirror",
  "burned",
  "jackpot_pool", // v1.1: progressive jackpot pool (specs/03)
] as const;
export type AccountKind = (typeof ACCOUNT_KINDS)[number];
export const accountKindEnum = pgEnum("account_kind", ACCOUNT_KINDS);

// Reuse shared zod enum string values so the wire contract and pg enums cannot drift.
export const factionEnum = pgEnum("faction", faction.options);
export const characterStatusEnum = pgEnum("character_status", characterStatus.options);
export const missionStateEnum = pgEnum("mission_state", missionState.options);
export const missionOutcomeEnum = pgEnum("mission_outcome", missionOutcome.options);

export const depositStateEnum = pgEnum("deposit_state", [
  "pending",
  "finalized",
  "credited",
  "unattributed",
]);
export const withdrawalStateEnum = pgEnum("withdrawal_state", [
  "queued",
  "review",
  "sent",
  "failed",
  "denied",
]);
export const mintEventStateEnum = pgEnum("mint_event_state", [
  "upcoming",
  "open",
  "soldout",
  "closed",
]);
export const mintOrderStateEnum = pgEnum("mint_order_state", [
  "pending",
  "fulfilled",
  "failed_retry",
]);
export const cosmeticSlotEnum = pgEnum("cosmetic_slot", [
  "hat",
  "coat",
  "mask",
  "companion",
  "banner",
  "nameplate",
]);
export const cosmeticRarityEnum = pgEnum("cosmetic_rarity", [
  "common",
  "rare",
  "epic",
  "legendary",
]);
export const raffleTypeEnum = pgEnum("raffle_type", ["recruitment", "cosmetic"]);
export const raffleStateEnum = pgEnum("raffle_state", ["upcoming", "open", "drawing", "drawn"]);
export const listingKindEnum = pgEnum("listing_kind", ["character", "cosmetic"]);
export const listingStateEnum = pgEnum("listing_state", ["active", "sold", "delisted"]);
/* v1.1 launch-scope enums (specs/02, specs/03). */
export const jackpotEventKindEnum = pgEnum("jackpot_event_kind", ["seed", "win"]);
export const passTrackEnum = pgEnum("pass_track", ["free", "premium"]);
export const passRewardKindEnum = pgEnum("pass_reward_kind", [
  "cosmetic",
  "insurance_voucher",
  "raffle_fragments",
  "nameplate",
]);

/* ── Identity ─────────────────────────────────────────────────────── */

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  handle: text("handle").notNull().unique(),
  role: userRoleEnum("role").notNull().default("player"),
  isGuest: boolean("is_guest").notNull().default(false),
  tosVersion: text("tos_version"),
  feedAnonymous: boolean("feed_anonymous").notNull().default(false),
  frozen: boolean("frozen").notNull().default(false),
  /* v1.1 Street Cred (specs/01): denormalized tier + downgrade-grace tracking. */
  currentTier: text("current_tier").notNull().default("none"),
  tierGraceStartedAt: timestamp("tier_grace_started_at", { withTimezone: true }),
  tierGraceTarget: text("tier_grace_target"),
  /* v1.1 Season Pass (specs/02): free single-mission insurance vouchers held. */
  insuranceVouchers: integer("insurance_vouchers").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const wallets = pgTable("wallets", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  address: text("address").notNull().unique(),
  chain: text("chain").notNull().default("solana"),
  isPrimary: boolean("is_primary").notNull().default(false),
  pendingPrimaryAt: timestamp("pending_primary_at", { withTimezone: true }),
});

export const sessions = pgTable("sessions", {
  /** Opaque session token (not a uuid — generated by the auth service). */
  id: text("id").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  fingerprintHash: text("fingerprint_hash"),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/* ── Ledger ───────────────────────────────────────────────────────── */

export const accounts = pgTable("accounts", {
  id: uuid("id").primaryKey().defaultRandom(),
  ownerType: accountOwnerTypeEnum("owner_type").notNull(),
  /** null for system singletons. Uniqueness enforced via partial indexes in sql.ts:
   *  - (owner_id, kind) UNIQUE WHERE owner_id IS NOT NULL
   *  - (kind) UNIQUE WHERE owner_type = 'system' AND owner_id IS NULL */
  ownerId: uuid("owner_id"),
  kind: accountKindEnum("kind").notNull(),
  currency: text("currency").notNull().default("SHINY"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * One logical double-entry transaction. idempotency_key is UNIQUE here (the parent),
 * so a logical txn's 2+ legs in ledger_entries can share one key safely.
 */
export const ledgerTxns = pgTable("ledger_txns", {
  id: uuid("id").primaryKey().defaultRandom(),
  idempotencyKey: text("idempotency_key").notNull().unique(),
  refType: text("ref_type"),
  refId: text("ref_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const ledgerEntries = pgTable("ledger_entries", {
  id: uuid("id").primaryKey().defaultRandom(),
  txnId: uuid("txn_id")
    .notNull()
    .references(() => ledgerTxns.id),
  accountId: uuid("account_id")
    .notNull()
    .references(() => accounts.id),
  /** CHECK (delta <> 0) enforced in sql.ts. */
  delta: bigint("delta", { mode: "bigint" }).notNull(),
  currency: text("currency").notNull().default("SHINY"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/* ── World / game ─────────────────────────────────────────────────── */

export const locations = pgTable("locations", {
  slug: text("slug").primaryKey(),
  name: text("name").notNull(),
  config: jsonb("config").$type<Record<string, unknown>>().notNull().default({}),
  enabled: boolean("enabled").notNull().default(true),
});

export const characters = pgTable("characters", {
  id: uuid("id").primaryKey().defaultRandom(),
  ownerUserId: uuid("owner_user_id")
    .notNull()
    .references(() => users.id),
  nftMint: text("nft_mint"),
  name: text("name").notNull(),
  faction: factionEnum("faction").notNull(),
  level: integer("level").notNull().default(1),
  stats: jsonb("stats").$type<CharacterStats>().notNull(),
  /** Deterministic appearance seed — drives the layered SVG art. */
  dna: text("dna").notNull(),
  status: characterStatusEnum("status").notNull().default("idle"),
  stationedAt: text("stationed_at"),
  jailedUntil: timestamp("jailed_until", { withTimezone: true }),
  inGame: boolean("in_game").notNull().default(true),
  lastClaimedAt: timestamp("last_claimed_at", { withTimezone: true }),
  cosmetics: jsonb("cosmetics").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const missions = pgTable("missions", {
  id: uuid("id").primaryKey().defaultRandom(),
  characterId: uuid("character_id").references(() => characters.id),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  locationSlug: text("location_slug")
    .notNull()
    .references(() => locations.slug),
  stake: bigint("stake", { mode: "bigint" }).notNull(),
  state: missionStateEnum("state").notNull().default("active"),
  serverSeedHash: text("server_seed_hash").notNull(),
  /** Encrypted at rest until reveal (resolution). */
  serverSeedEnc: text("server_seed_enc"),
  clientSeed: text("client_seed").notNull(),
  effectiveTable: jsonb("effective_table").$type<ProbabilityTable>().notNull(),
  insurance: boolean("insurance").notNull().default(false),
  bribed: boolean("bribed").notNull().default(false),
  freeTier: boolean("free_tier").notNull().default(false),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
  resolvesAt: timestamp("resolves_at", { withTimezone: true }).notNull(),
});

export const missionOutcomes = pgTable("mission_outcomes", {
  missionId: uuid("mission_id")
    .primaryKey()
    .references(() => missions.id),
  outcome: missionOutcomeEnum("outcome").notNull(),
  payout: bigint("payout", { mode: "bigint" }).notNull(),
  serverSeed: text("server_seed").notNull(),
  roll: doublePrecision("roll").notNull(),
  detail: jsonb("detail").$type<Record<string, unknown>>(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const patrols = pgTable("patrols", {
  id: uuid("id").primaryKey().defaultRandom(),
  characterId: uuid("character_id")
    .notNull()
    .references(() => characters.id),
  locationSlug: text("location_slug").notNull(),
  weight: doublePrecision("weight").notNull(),
  shiftStart: timestamp("shift_start", { withTimezone: true }).notNull(),
  shiftEnd: timestamp("shift_end", { withTimezone: true }).notNull(),
  active: boolean("active").notNull().default(true),
});

/* ── Bank ─────────────────────────────────────────────────────────── */

export const deposits = pgTable("deposits", {
  id: uuid("id").primaryKey().defaultRandom(),
  /** Nullable: deposits without a valid memo land 'unattributed' for manual review. */
  userId: uuid("user_id").references(() => users.id),
  txSig: text("tx_sig").notNull().unique(),
  amount: bigint("amount", { mode: "bigint" }).notNull(),
  state: depositStateEnum("state").notNull().default("pending"),
  memo: text("memo"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const depositMemos = pgTable("deposit_memos", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  memo: text("memo").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const withdrawals = pgTable("withdrawals", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  amount: bigint("amount", { mode: "bigint" }).notNull(),
  fee: bigint("fee", { mode: "bigint" }).notNull(),
  destAddress: text("dest_address").notNull(),
  state: withdrawalStateEnum("state").notNull().default("queued"),
  txSig: text("tx_sig"),
  reason: text("reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  processedAt: timestamp("processed_at", { withTimezone: true }),
});

/* ── Mint ─────────────────────────────────────────────────────────── */

export const mintEvents = pgTable("mint_events", {
  id: uuid("id").primaryKey().defaultRandom(),
  faction: factionEnum("faction").notNull(),
  price: bigint("price", { mode: "bigint" }).notNull(),
  supply: integer("supply").notNull(),
  remaining: integer("remaining").notNull(),
  opensAt: timestamp("opens_at", { withTimezone: true }).notNull(),
  closesAt: timestamp("closes_at", { withTimezone: true }).notNull(),
  state: mintEventStateEnum("state").notNull().default("upcoming"),
});

export const mintOrders = pgTable("mint_orders", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  eventId: uuid("event_id")
    .notNull()
    .references(() => mintEvents.id),
  state: mintOrderStateEnum("state").notNull().default("pending"),
  characterId: uuid("character_id"),
  idempotencyKey: text("idempotency_key").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/* ── Cosmetics / raffles / marketplace ────────────────────────────── */

export const cosmeticItems = pgTable("cosmetic_items", {
  slug: text("slug").primaryKey(),
  name: text("name").notNull(),
  slot: cosmeticSlotEnum("slot").notNull(),
  rarity: cosmeticRarityEnum("rarity").notNull(),
  priceShiny: bigint("price_shiny", { mode: "bigint" }),
  priceSol: doublePrecision("price_sol"),
  supplyCap: integer("supply_cap"),
  sold: integer("sold").notNull().default(0),
  season: integer("season").notNull(),
  description: text("description").notNull(),
  artUri: text("art_uri"),
});

export const userCosmetics = pgTable("user_cosmetics", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  itemSlug: text("item_slug")
    .notNull()
    .references(() => cosmeticItems.slug),
  equippedCharacterId: uuid("equipped_character_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const raffles = pgTable("raffles", {
  id: uuid("id").primaryKey().defaultRandom(),
  type: raffleTypeEnum("type").notNull(),
  title: text("title").notNull(),
  prize: jsonb("prize").$type<Record<string, unknown>>().notNull(),
  ticketPrice: bigint("ticket_price", { mode: "bigint" }).notNull(),
  maxTickets: integer("max_tickets"),
  opensAt: timestamp("opens_at", { withTimezone: true }).notNull(),
  drawsAt: timestamp("draws_at", { withTimezone: true }).notNull(),
  serverSeedHash: text("server_seed_hash").notNull(),
  serverSeed: text("server_seed"),
  state: raffleStateEnum("state").notNull().default("upcoming"),
  winners: jsonb("winners").$type<unknown[]>(),
});

export const raffleTickets = pgTable("raffle_tickets", {
  id: uuid("id").primaryKey().defaultRandom(),
  raffleId: uuid("raffle_id")
    .notNull()
    .references(() => raffles.id),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  count: integer("count").notNull(),
});

export const loginFragments = pgTable(
  "login_fragments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    day: date("day").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userDayUq: uniqueIndex("login_fragments_user_day_uq").on(t.userId, t.day),
  }),
);

export const listings = pgTable("listings", {
  id: uuid("id").primaryKey().defaultRandom(),
  sellerId: uuid("seller_id")
    .notNull()
    .references(() => users.id),
  kind: listingKindEnum("kind").notNull(),
  /** characters.id or user_cosmetics.id depending on kind. */
  refId: uuid("ref_id").notNull(),
  price: bigint("price", { mode: "bigint" }).notNull(),
  state: listingStateEnum("state").notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  soldAt: timestamp("sold_at", { withTimezone: true }),
  buyerId: uuid("buyer_id"),
});

/* ── Ops / telemetry ──────────────────────────────────────────────── */

export const sybilFlags = pgTable("sybil_flags", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  clusterKey: text("cluster_key").notNull(),
  severity: text("severity").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const reservesSnapshots = pgTable("reserves_snapshots", {
  id: uuid("id").primaryKey().defaultRandom(),
  at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
  onchainHot: bigint("onchain_hot", { mode: "bigint" }).notNull(),
  onchainMultisig: bigint("onchain_multisig", { mode: "bigint" }).notNull(),
  liabilities: bigint("liabilities", { mode: "bigint" }).notNull(),
  healthy: boolean("healthy").notNull(),
});

/** Kill switches & tunables. */
export const configKv = pgTable("config_kv", {
  key: text("key").primaryKey(),
  value: jsonb("value").$type<unknown>().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/** One-way ratchet timelock for config changes. */
export const pendingChanges = pgTable("pending_changes", {
  id: uuid("id").primaryKey().defaultRandom(),
  key: text("key").notNull(),
  value: jsonb("value").$type<unknown>().notNull(),
  effectiveAt: timestamp("effective_at", { withTimezone: true }).notNull(),
  applied: boolean("applied").notNull().default(false),
});

export const pdDistributions = pgTable("pd_distributions", {
  id: uuid("id").primaryKey().defaultRandom(),
  day: date("day").notNull().unique(),
  poolSnapshot: bigint("pool_snapshot", { mode: "bigint" }).notNull(),
  distributed: bigint("distributed", { mode: "bigint" }).notNull(),
  recipients: integer("recipients").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const incidents = pgTable("incidents", {
  id: uuid("id").primaryKey().defaultRandom(),
  kind: text("kind").notNull(),
  severity: text("severity").notNull(),
  detail: jsonb("detail").$type<Record<string, unknown>>(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  resolved: boolean("resolved").notNull().default(false),
});

export const auditLog = pgTable("audit_log", {
  id: uuid("id").primaryKey().defaultRandom(),
  actor: text("actor").notNull(),
  action: text("action").notNull(),
  detail: jsonb("detail").$type<Record<string, unknown>>(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/* ── v1.1 launch scope: jackpot / street cred / season pass ───────── */

/** Progressive jackpot history: the 2M seed + every pool win (specs/03). */
export const jackpotEvents = pgTable("jackpot_events", {
  id: uuid("id").primaryKey().defaultRandom(),
  kind: jackpotEventKindEnum("kind").notNull(),
  missionId: uuid("mission_id"),
  userId: uuid("user_id"),
  amount: bigint("amount", { mode: "bigint" }).notNull(),
  poolAfter: bigint("pool_after", { mode: "bigint" }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Street Cred snapshots: daily job + on-demand resolution (specs/01). */
export const tierSnapshots = pgTable("tier_snapshots", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  wallet: text("wallet"),
  balance: bigint("balance", { mode: "bigint" }).notNull(),
  tier: text("tier").notNull(),
  snapshottedAt: timestamp("snapshotted_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Tier thresholds + perks, seeded from shared TIER_DEFINITIONS; thresholds move
 *  only through the 7-day-notice timelock (pending_changes). */
export const tierDefinitions = pgTable("tier_definitions", {
  tier: text("tier").primaryKey(),
  minBalance: bigint("min_balance", { mode: "bigint" }).notNull(),
  perks: jsonb("perks").$type<Record<string, unknown>>().notNull(),
});

/** Season Pass purchases — one per user per season (specs/02). */
export const seasonPasses = pgTable(
  "season_passes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    season: integer("season").notNull(),
    premium: boolean("premium").notNull().default(false),
    purchasedAt: timestamp("purchased_at", { withTimezone: true }).notNull().defaultNow(),
    txSig: text("tx_sig"),
  },
  (t) => ({
    userSeasonUq: uniqueIndex("season_passes_user_season_uq").on(t.userId, t.season),
  }),
);

export const passProgress = pgTable(
  "pass_progress",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    season: integer("season").notNull(),
    xp: integer("xp").notNull().default(0),
    level: integer("level").notNull().default(0),
  },
  (t) => ({
    userSeasonUq: uniqueIndex("pass_progress_user_season_uq").on(t.userId, t.season),
  }),
);

export const passChallenges = pgTable("pass_challenges", {
  id: uuid("id").primaryKey().defaultRandom(),
  season: integer("season").notNull(),
  week: integer("week").notNull(),
  slug: text("slug").notNull().unique(),
  description: text("description").notNull(),
  /** missions_at_location | wins_anywhere | survive_location | bail_outs | raffle_tickets */
  kind: text("kind").notNull(),
  refSlug: text("ref_slug"),
  target: integer("target").notNull(),
  xp: integer("xp").notNull(),
});

export const passChallengeProgress = pgTable(
  "pass_challenge_progress",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    challengeId: uuid("challenge_id")
      .notNull()
      .references(() => passChallenges.id),
    progress: integer("progress").notNull().default(0),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (t) => ({
    userChallengeUq: uniqueIndex("pass_challenge_progress_user_challenge_uq").on(
      t.userId,
      t.challengeId,
    ),
  }),
);

/** Iron rule (doc 13 §4): rewards are flex only — never $SHINY, never stats. */
export const passRewards = pgTable(
  "pass_rewards",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    season: integer("season").notNull(),
    level: integer("level").notNull(),
    track: passTrackEnum("track").notNull(),
    kind: passRewardKindEnum("kind").notNull(),
    refSlug: text("ref_slug"),
    amount: integer("amount"),
  },
  (t) => ({
    seasonLevelTrackUq: uniqueIndex("pass_rewards_season_level_track_uq").on(
      t.season,
      t.level,
      t.track,
    ),
  }),
);

export const passClaims = pgTable(
  "pass_claims",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    rewardId: uuid("reward_id")
      .notNull()
      .references(() => passRewards.id),
    claimedAt: timestamp("claimed_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userRewardUq: uniqueIndex("pass_claims_user_reward_uq").on(t.userId, t.rewardId),
  }),
);

/** Borough+ weekly raffle-ticket grants — idempotent per (user, ISO week). */
export const raffleWeeklyGrants = pgTable(
  "raffle_weekly_grants",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    week: text("week").notNull(),
    raffleId: uuid("raffle_id")
      .notNull()
      .references(() => raffles.id),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userWeekUq: uniqueIndex("raffle_weekly_grants_user_week_uq").on(t.userId, t.week),
  }),
);

/** Persisted city feed backing the ticker. */
export const feedEvents = pgTable("feed_events", {
  id: uuid("id").primaryKey().defaultRandom(),
  type: text("type").notNull(),
  locationSlug: text("location_slug"),
  actor: text("actor"),
  multiplierBps: integer("multiplier_bps"),
  amountBand: text("amount_band"),
  message: text("message").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
