import { toBaseUnits, type CosmeticItem } from "@trash-wars/shared";

const u = (whole: number): string => toBaseUnits(whole).toString();

/**
 * Local policy knobs that the shared packages don't define (yet).
 * GAP: bribe price bps is "configured" server-side per doc 08 but absent from
 * shared POLICY — we pin the beta value here.
 */
export const LOCAL_POLICY = {
  bribePriceBps: 300, // 3% of stake, 75% burn / 25% to patrolling hounds
  faucetAmount: toBaseUnits(100_000),
  faucetCooldownGameHours: 24,
  starterBalance: toBaseUnits(100_000),
  loginFragmentsPerTicket: 5,
} as const;

/** Season-1 cosmetics catalogue (beta). Slugs double as avatar layer keys. */
export const STORE_ITEMS: CosmeticItem[] = [
  {
    slug: "hat-fedora",
    name: "Rainline Fedora",
    slot: "hat",
    rarity: "common",
    priceShiny: u(2_000),
    priceSol: null,
    supplyCap: null,
    remaining: null,
    season: 1,
    description: "Keeps the rain out of your eyes and the cameras off your face.",
  },
  {
    slug: "hat-beanie",
    name: "Dock Worker Beanie",
    slot: "hat",
    rarity: "common",
    priceShiny: u(1_200),
    priceSol: null,
    supplyCap: null,
    remaining: null,
    season: 1,
    description: "Standard issue for anyone who's ever cased a warehouse.",
  },
  {
    slug: "hat-crown",
    name: "Dumpster Crown",
    slot: "hat",
    rarity: "legendary",
    priceShiny: u(50_000),
    priceSol: null,
    supplyCap: 25,
    remaining: 11,
    season: 1,
    description: "Somebody threw out a kingdom. You wear what's left of it.",
  },
  {
    slug: "mask-visor",
    name: "Neon Visor",
    slot: "mask",
    rarity: "epic",
    priceShiny: u(15_000),
    priceSol: null,
    supplyCap: 200,
    remaining: 84,
    season: 1,
    description: "See in the dark. Be seen in the dark. Tradeoffs.",
  },
  {
    slug: "coat-trench",
    name: "Shorefront Trench",
    slot: "coat",
    rarity: "rare",
    priceShiny: u(6_000),
    priceSol: null,
    supplyCap: null,
    remaining: null,
    season: 1,
    description: "Four inside pockets. None of them are for your own stuff.",
  },
  {
    slug: "companion-pigeon",
    name: "Lookout Pigeon",
    slot: "companion",
    rarity: "rare",
    priceShiny: u(8_000),
    priceSol: null,
    supplyCap: null,
    remaining: null,
    season: 1,
    description: "Coos twice if the heat's coming. Usually.",
  },
  {
    slug: "banner-skyline",
    name: "Skyline Banner",
    slot: "banner",
    rarity: "common",
    priceShiny: u(1_500),
    priceSol: null,
    supplyCap: null,
    remaining: null,
    season: 1,
    description: "Your profile, but make it noir.",
  },
  {
    slug: "nameplate-gilded",
    name: "Gilded Nameplate",
    slot: "nameplate",
    rarity: "epic",
    priceShiny: null,
    priceSol: 0.25,
    supplyCap: 500,
    remaining: 500,
    season: 1,
    description: "Premium rail. Arrives with mainnet — SOL checkout coming soon.",
  },
];

/** Noir bot roster names (40). Mix of raccoons and bloodhounds. */
export const BOT_NAMES: ReadonlyArray<{ name: string; faction: "raccoon" | "bloodhound" }> = [
  { name: "Velvet Knuckles", faction: "raccoon" },
  { name: "Two-Step Tibbs", faction: "raccoon" },
  { name: "Marlowe the Damp", faction: "raccoon" },
  { name: "Sister Static", faction: "raccoon" },
  { name: "Greasy Calhoun", faction: "raccoon" },
  { name: "The Pale Bandit", faction: "raccoon" },
  { name: "Nickels", faction: "raccoon" },
  { name: "Madame Forklift", faction: "raccoon" },
  { name: "Sad Eyes Sal", faction: "raccoon" },
  { name: "Brick Tooth", faction: "raccoon" },
  { name: "Lullaby Lou", faction: "raccoon" },
  { name: "The Mayor of Nothing", faction: "raccoon" },
  { name: "Quiet Jenny", faction: "raccoon" },
  { name: "Half-Pint Hugo", faction: "raccoon" },
  { name: "Cufflinks", faction: "raccoon" },
  { name: "Riverside Rosa", faction: "raccoon" },
  { name: "Smokestack Eddie", faction: "raccoon" },
  { name: "The Insurance Salesman", faction: "raccoon" },
  { name: "Penny Dreadful", faction: "raccoon" },
  { name: "Glasshouse Gus", faction: "raccoon" },
  { name: "Mittens DeLuca", faction: "raccoon" },
  { name: "Foggy Pete", faction: "raccoon" },
  { name: "The Archivist", faction: "raccoon" },
  { name: "Switchblade Sue", faction: "raccoon" },
  { name: "Old Turnstile", faction: "raccoon" },
  { name: "Caviar Carl", faction: "raccoon" },
  { name: "Wet Sock Willy", faction: "raccoon" },
  { name: "Duchess of Dumpsters", faction: "raccoon" },
  { name: "Three-Finger Fitz", faction: "raccoon" },
  { name: "Neon Nadia", faction: "raccoon" },
  { name: "Officer Rex", faction: "bloodhound" },
  { name: "Sgt. Slobber", faction: "bloodhound" },
  { name: "K9-Magnus", faction: "bloodhound" },
  { name: "Detective Drool", faction: "bloodhound" },
  { name: "Warrant", faction: "bloodhound" },
  { name: "Captain Bayou", faction: "bloodhound" },
  { name: "The Bloodhound General", faction: "bloodhound" },
  { name: "Patrolman Pudge", faction: "bloodhound" },
  { name: "Inspector Howl", faction: "bloodhound" },
  { name: "Deputy Dewlap", faction: "bloodhound" },
];

export const EMPTY_LINES = {
  feed: "Nothing but rain out here.",
  jail: "Nobody's in the tank. Keep it that way.",
  missions: "No jobs running. The city won't rob itself.",
  market: "Shelves are bare. Somebody clean this place out already?",
  den: "An empty den. Even the rats moved somewhere nicer.",
  patrols: "No hounds on the street tonight.",
  history: "No paper trail. The way you like it.",
} as const;
